---
# Test group_vars
- hosts: "{{ stack }}"
  gather_facts: no
  become: true

  vars:
    template_source: files/weblogic
    host_vars: "{{ hostvars[inventory_hostname] }}"
    domain_vars: "{{ host_vars['%s' | format(domain_name)] }}"
    common_vars: "{{ host_vars['%s_common' | format(domain_name)] }}"
    server_vars: "{{ host_vars['%s_servers' | format(domain_name)] }}"
    server_common: "{{server_vars.server_common}}"

  tasks:
    - name: start node manager
      become: yes
      become_user: dev50
      # shell: cd /u02/oracle/scripts/dev50/bin; nohup ./admin-nodemanager.sh </dev/null >/dev/null 2>&1 &
      shell: nohup /u02/oracle/scripts/dev50/bin/admin-nodemanager.sh </dev/null >/dev/null 2>&1 &
      args:
        chdir: /u02/oracle/scripts/dev50/bin
      when: (is_admin_server is defined and is_admin_server )
