---
# task to create systemd services to start and stop nodemanager and admin server
- name: Copy nodemanager systemd to servers
  become: yes
  template:
    src: nodemanager.service.j2
    dest: "/etc/systemd/system/nodemanager-{{ domain_name }}.service"
    mode: u=rw,g=r,o=r
  tags:
    - linux

- name: Copy admin systemd to server running the admin server only
  become: yes
  template:
    src: adminserver.service.j2
    dest: "/etc/systemd/system/adminserver-{{ domain_name }}.service"
    mode: u=rw,g=r,o=r
  when: (is_admin_server is defined and is_admin_server )
  tags:
    - linux
