---
# Group vars that will be used to configure servers
a5d50d1_common:
  oracle_home: /u01/oracle
  fmw_home: /u01/oracle/products/fmw/12.2.1.3.0
  domain_owner: dev50
  fmw_group: mwg
  java_home: /u01/oracle/products/jdk/jdk1.8.0_241
  scripts_home: /u02/oracle/scripts/{{ stack | regex_replace('^stack_', '') }}
  domain_dir: /u02/oracle/config/domains/{{ stack | regex_replace('^stack_', '') }}
  utils_script_home: /u02/oracle/config/domains/{{ stack | regex_replace('^stack_', '') }}/utils
  log_root_dir: /u02/oracle/config/domains/logs
  log_dir: /u02/oracle/config/domains/logs/{{ stack | regex_replace('^stack_', '') }}
  log_rotation_root_dir: /u02/oracle/config/domains/logs/{{ stack | regex_replace('^stack_', '') }}/servers/history
  date_format: "yyyy-MM-dd_HH:mm:ss:SSS_zzz"
  access_log_format: "c-ip date time cs-method sc-status bytes time-taken cs-uri cs(Referer) cs(User-Agent)"
  applications_root_dir: /u02/oracle/config/domains/applications
  applications_dir: /u02/oracle/config/domains/applications/{{ stack | regex_replace('^stack_', '') }}
  ssl_keystore_dir: /u02/oracle/config/domains/security
  ssl_key_type: JKS
  ssl_key_pass_phrase: cpowebops
  server_private_key_alias: dev51-soa-san
  key_stores: CustomIdentityAndCustomTrust
  indentity_store: CPGIdentity.jks
  trust_store:  CPGTrust.jks
  log_buffer_size: 0
  log_file_count: 14
  utf_arg: "-Dfile.encoding=UTF-8"
  hosts:
    host_adm: 192.168.99.40 #stg-wladm.cpggpc.ca
    mgnt_adm: stg-wladm-mgnt.cpggpc.ca
    host_a: stg-a-soaz0.cpggpc.ca
    host_b: stg-b-soaz0.cpggpc.ca
    host_c: stg-c-soaz0.cpggpc.ca
    host_d: stg-d-soaz0.cpggpc.ca
    mgnt_a: stg-a-soaz0-mgnt.cpggpc.ca
    mgnt_b: stg-b-soaz0-mgnt.cpggpc.ca
    mgnt_c: stg-c-soaz0-mgnt.cpggpc.ca
    mgnt_d: stg-d-soaz0-mgnt.cpggpc.ca
