---
- name: set variables - will be used repeatedly
  set_fact:
    rcu_scripts_dir: "{{ common_vars.scripts_home }}/{{ domain_name }}/bin"

- name: create directory to put scripts etc
  file:
    path: "{{ rcu_scripts_dir }}"
    state: directory
    group: "{{ fmw_group }}"
    mode: g=rw

- name: copy create repository shell script to the scripts directory
  template:
    src: "{{ item }}"
    dest: "{{ rcu_scripts_dir }}/{{ item | basename | regex_replace('\\.j2$') }}"
    owner: "{{ domain_owner  }}"
    group: "{{ fmw_group }}"
    mode: u=rwx,g=r,o-rwx
  loop:
    - create-repository.sh.j2
    - drop-repository.sh.j2

# - name: run rcu to crate schema and populate it
#   shell:
#     cmd: "{{ domain_scripts_dir }}/bin/create-repository.sh"
